export const EXERCISE_INITIAL_STATUS = 'EXERCISE_INITIAL_STATUS';
export const EXERCISE_STARTING_STATUS = 'EXERCISE_STARTING_STATUS';
export const EXERCISE_RUNNING_STATUS = 'EXERCISE_RUNNING_STATUS';
