export const STREAM_STATUS_INITIAL = 'STREAM_STATUS_INITIAL';
export const STREAM_STATUS_LOADING = 'STREAM_STATUS_LOADING';
export const STREAM_STATUS_LOADED = 'STREAM_STATUS_LOADED';
export const STREAM_STATUS_ERROR = 'STREAM_STATUS_ERROR';